FROM node:16-alpine

WORKDIR /app/

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./frontend/package.json ./frontend/package.json
COPY ./dapps-lib/package.json ./dapps-lib/package.json
COPY ./injected-connector/package.json ./injected-connector/package.json
RUN npm ci

COPY ./frontend ./frontend
COPY ./dapps-lib ./dapps-lib
COPY ./injected-connector ./injected-connector
WORKDIR /app/frontend/

CMD npm run start