# Generated by Django 3.2.6 on 2022-12-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_table', '0002_burnhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='burn',
            name='status',
            field=models.CharField(choices=[('NOT_EXIST', 'Not Exist'), ('BURN_INITIATED', 'Burn Initiated'), ('BURN_COMPLETED', 'Burn Completed')], default='NOT_EXIST', max_length=20),
        ),
        migrations.AddField(
            model_name='mint',
            name='status',
            field=models.CharField(choices=[('NOT_EXIST', 'Not Exist'), ('MINT_INITIATED', 'Mint Initiated'), ('MINT_COMPLETED', 'Mint Completed')], default='NOT_EXIST', max_length=20),
        ),
        migrations.AlterField(
            model_name='barholder',
            name='token_balance',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='burnhistory',
            name='adjusted_amount',
            field=models.CharField(max_length=36),
        ),
    ]
