# Generated by Django 3.2.6 on 2022-11-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_table', '0002_burnhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditBarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Edit Bar Status',
                'verbose_name_plural': 'Edit Bar Status',
            },
        ),
    ]
