# Generated by Django 3.2.6 on 2022-12-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_table', '0003_auto_20221215_0837'),
        ('core_table', '0003_editbarstatus'),
    ]

    operations = [
    ]
