# Generated by Django 3.2.6 on 2023-02-17 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_table', '0004_merge_0003_auto_20221215_0837_0003_editbarstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barholder',
            name='holder_date',
            field=models.DateField(auto_created=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='burn',
            name='burnt_date',
            field=models.DateField(auto_created=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='burnhistory',
            name='burnt_date',
            field=models.DateField(auto_created=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='goldbar',
            name='bar_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goldbar',
            name='escrow_date',
            field=models.DateField(auto_created=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='goldbar',
            name='warrant_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mint',
            name='mint_date',
            field=models.DateField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
