# Generated by Django 3.2.6 on 2022-08-06 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(default=0, help_text='Last block processed')),
                ('last_error_block_number', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoredEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contract_address', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)])),
                ('event_abi', models.TextField()),
                ('topic', models.CharField(max_length=66, validators=[django.core.validators.MinLengthValidator(66)])),
                ('event_receiver', models.CharField(max_length=256)),
                ('monitored_from', models.IntegerField(blank=True, help_text='Block number in which monitoring for this event started', null=True)),
            ],
            options={
                'verbose_name': 'Monitored Event',
                'verbose_name_plural': 'Monitored Events',
                'unique_together': {('topic', 'contract_address')},
            },
        ),
        migrations.CreateModel(
            name='FailedEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=256)),
                ('transaction_hash', models.CharField(max_length=66, validators=[django.core.validators.MinLengthValidator(66)])),
                ('transaction_index', models.IntegerField()),
                ('block_hash', models.CharField(max_length=66, validators=[django.core.validators.MinLengthValidator(66)])),
                ('block_number', models.IntegerField()),
                ('log_index', models.IntegerField()),
                ('address', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)])),
                ('args', models.TextField(default='{}')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('monitored_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_events', to='django_ethereum_events.monitoredevent')),
            ],
            options={
                'verbose_name': 'Failed to process Event',
                'verbose_name_plural': 'Failed to process Events',
            },
        ),
    ]
